// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3yRIaAnqtA4Ihjy-kLRjopGdyoFRptGA',
    appId: '1:791928970814:web:68ae0930ea25198f8ffb6f',
    messagingSenderId: '791928970814',
    projectId: 'sahaay-app-01-cf6e7',
    authDomain: 'sahaay-app-01-cf6e7.firebaseapp.com',
    storageBucket: 'sahaay-app-01-cf6e7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqGSiqPwZhC6SPDaT7oc12BxBXXbtNKZI',
    appId: '1:791928970814:android:5f0fd4a580867b308ffb6f',
    messagingSenderId: '791928970814',
    projectId: 'sahaay-app-01-cf6e7',
    storageBucket: 'sahaay-app-01-cf6e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD83rTafMJo2mE167kOL0IEMBsdkczLlkA',
    appId: '1:791928970814:ios:2c20d0279c412b618ffb6f',
    messagingSenderId: '791928970814',
    projectId: 'sahaay-app-01-cf6e7',
    storageBucket: 'sahaay-app-01-cf6e7.firebasestorage.app',
    iosBundleId: 'com.sahaay.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD83rTafMJo2mE167kOL0IEMBsdkczLlkA',
    appId: '1:791928970814:ios:2c20d0279c412b618ffb6f',
    messagingSenderId: '791928970814',
    projectId: 'sahaay-app-01-cf6e7',
    storageBucket: 'sahaay-app-01-cf6e7.firebasestorage.app',
    iosBundleId: 'com.sahaay.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3yRIaAnqtA4Ihjy-kLRjopGdyoFRptGA',
    appId: '1:791928970814:web:bf835e99a446ea908ffb6f',
    messagingSenderId: '791928970814',
    projectId: 'sahaay-app-01-cf6e7',
    authDomain: 'sahaay-app-01-cf6e7.firebaseapp.com',
    storageBucket: 'sahaay-app-01-cf6e7.firebasestorage.app',
  );
}
